# Generated by Django 5.1.7 on 2025-05-19 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('nature', models.CharField(choices=[('Software Development', 'Software Development'), ('Web Services', 'Web Services'), ('Mobile Apps', 'Mobile Apps'), ('Desktop Apps', 'Desktop Apps'), ('IoT Apps', 'IoT Apps')], default='Software Development', max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('Idea', 'Idea'), ('MVP', 'MVP'), ('Early-stage', 'Early-stage'), ('Growth', 'Growth'), ('Scaling', 'Scaling')], default='Idea', max_length=50)),
                ('official_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('registration_number', models.CharField(default='CPR/201x/xxxxx', max_length=255)),
                ('contact_person', models.CharField(default='John Doe', max_length=255)),
                ('date_of_establishment', models.DateField()),
                ('physical_address', models.TextField()),
                ('tax_identification_number', models.CharField(max_length=100)),
                ('employees', models.IntegerField()),
                ('company_description', models.TextField()),
                ('nature', models.CharField(choices=[('Software Development', 'Software Development'), ('Web Services', 'Web Services'), ('Mobile Apps', 'Mobile Apps'), ('Desktop Apps', 'Desktop Apps'), ('IoT Apps', 'IoT Apps')], default='Software Development', max_length=50)),
                ('specialization', models.CharField(default='Web Development', max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('business_model', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('SaaS', 'SaaS'), ('Marketplace', 'Marketplace')], max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingPage.signupuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
