# Generated by Django 5.1.7 on 2025-04-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('Idea', 'Idea'), ('MVP', 'MVP'), ('Early-stage', 'Early-stage'), ('Growth', 'Growth'), ('Scaling', 'Scaling')], max_length=50)),
                ('official_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_establishment', models.DateField()),
                ('physical_address', models.TextField()),
                ('tax_identification_number', models.CharField(max_length=100)),
                ('employees', models.IntegerField()),
                ('startup_description', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('business_model', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('SaaS', 'SaaS'), ('Marketplace', 'Marketplace')], max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
