# Generated by Django 5.1.7 on 2025-04-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='startup_description',
            new_name='company_description',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='startup_name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='individualdev',
            name='nature',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Web Services', 'Web Services'), ('Mobile Apps', 'Mobile Apps'), ('Desktop Apps', 'Desktop Apps'), ('IoT Apps', 'IoT Apps')], default='Software Development', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='contact_person',
            field=models.CharField(default='John Doe', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='nature',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Web Services', 'Web Services'), ('Mobile Apps', 'Mobile Apps'), ('Desktop Apps', 'Desktop Apps'), ('IoT Apps', 'IoT Apps')], default='Software Development', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(default='CPR/201x/xxxxx', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='specialization',
            field=models.CharField(default='Web Development', max_length=255),
        ),
    ]
