# Generated by Django 5.1.7 on 2025-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_registration_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdev',
            name='nature',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Web Services', 'Web Services'), ('Mobile Apps', 'Mobile Apps'), ('Desktop Apps', 'Desktop Apps'), ('IoT Apps', 'IoT Apps'), ('Cloud Computing', 'Cloud Computing'), ('Game Development (including mobile games)', 'Game Development (including mobile games)'), ('Other', 'Other')], default='Software Development', max_length=50),
        ),
    ]
