# Generated by Django 5.2 on 2025-04-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_startup_description_registration_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='stage',
            field=models.CharField(choices=[('Idea', 'Idea'), ('MVP', 'MVP'), ('Early-stage', 'Early-stage'), ('Growth', 'Growth'), ('Scaling', 'Scaling')], default='Idea', max_length=50),
        ),
    ]
