# Generated by Django 5.1.7 on 2025-05-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_individualdev_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdev',
            name='nature',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Web Services', 'Web Services'), ('Mobile Apps', 'Mobile Apps'), ('Desktop Apps', 'Desktop Apps'), ('IoT Apps', 'IoT Apps')], default='Software Development', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nature',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Web Services', 'Web Services'), ('Mobile Apps', 'Mobile Apps'), ('Desktop Apps', 'Desktop Apps'), ('IoT Apps', 'IoT Apps')], default='Software Development', max_length=50),
        ),
    ]
