# Generated by Django 5.1.7 on 2025-05-06 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_individualdev_nature_alter_registration_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualdev',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
