# Generated by Django 5.1.7 on 2025-05-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_individualdev_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualdev',
            name='created_at',
        ),
    ]
