# Generated by Django 5.1.7 on 2025-03-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255)),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_establishment', models.DateField()),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('official_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('physical_address', models.TextField()),
                ('city_region', models.CharField(max_length=100)),
                ('founder_name', models.CharField(max_length=255)),
                ('founder_id', models.CharField(max_length=100)),
                ('founder_contact', models.CharField(max_length=20)),
                ('employees', models.IntegerField()),
                ('startup_description', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('business_model', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('SaaS', 'SaaS'), ('Marketplace', 'Marketplace')], max_length=50)),
                ('stage', models.CharField(choices=[('Idea', 'Idea'), ('MVP', 'MVP'), ('Early-stage', 'Early-stage'), ('Growth', 'Growth'), ('Scaling', 'Scaling')], max_length=50)),
                ('revenue_model', models.TextField()),
                ('core_technologies', models.TextField()),
                ('unique_value_proposition', models.TextField()),
                ('ip_ownership', models.TextField(blank=True, null=True)),
                ('funding_status', models.CharField(max_length=255)),
                ('key_investors', models.TextField(blank=True, null=True)),
                ('business_certificate', models.FileField(upload_to='certificates/')),
                ('tax_identification_number', models.CharField(max_length=100)),
                ('licenses', models.TextField(blank=True, null=True)),
                ('gdpr_compliance', models.BooleanField(default=False)),
                ('government_support_needed', models.TextField()),
                ('challenges_faced', models.TextField()),
                ('agree_terms', models.BooleanField(default=False)),
                ('consent_data_usage', models.BooleanField(default=False)),
                ('signature', models.TextField()),
            ],
        ),
    ]
