# Generated by Django 5.1.7 on 2025-04-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='agree_terms',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='business_certificate',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='business_registration_number',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='challenges_faced',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='city_region',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='consent_data_usage',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='core_technologies',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='founder_contact',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='founder_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='founder_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='funding_status',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='gdpr_compliance',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='government_support_needed',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='ip_ownership',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='key_investors',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='licenses',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='revenue_model',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='unique_value_proposition',
        ),
    ]
