# Generated by Django 5.2 on 2025-04-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupRegistration', '0002_remove_registration_agree_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('nature_of_business', models.CharField(max_length=255)),
                ('objectives', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('employees', models.PositiveIntegerField()),
            ],
        ),
    ]
