# Generated by Django 5.1.7 on 2025-04-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupRegistration', '0002_remove_registration_agree_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
