# Generated by Django 5.2 on 2025-04-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=255)),
                ('lName', models.CharField(max_length=255)),
                ('idNo', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('nationality', models.PositiveIntegerField()),
                ('county', models.PositiveIntegerField()),
                ('subcounty', models.PositiveIntegerField()),
                ('gender', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('password', models.TextField()),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('isLogin', models.BooleanField(default=False)),
                ('logtime', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'internalusers',
            },
        ),
    ]
