# Generated by Django 5.2 on 2025-05-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0002_loginattempt_passwordresettoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginAttempt',
            new_name='AttemptLogin',
        ),
        migrations.AlterModelTable(
            name='attemptlogin',
            table='attempt_login',
        ),
    ]
