# Generated by Django 5.2 on 2025-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0004_sysnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='pswdchange',
            field=models.BooleanField(default=True),
        ),
    ]
