# Generated by Django 5.2 on 2025-05-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0005_internaluser_pswdchange'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sysnotification',
            table='sys_notifications',
        ),
    ]
