# Generated by Django 5.2 on 2025-05-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='pswdchange',
            field=models.IntegerField(default=0),
        ),
    ]
