# Generated by Django 5.2 on 2025-05-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_signupuser_pswdchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='accountType',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupuser',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
