# Generated by Django 5.2 on 2025-05-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0003_signupuser_accounttype_signupuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='fName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signupuser',
            name='lName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
