# Generated by Django 5.1.7 on 2025-04-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0004_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=255)),
                ('lName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('nationality', models.IntegerField()),
                ('county', models.IntegerField()),
                ('subcounty', models.IntegerField()),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('password', models.TextField()),
                ('isLogin', models.IntegerField(default=0)),
                ('logtime', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'externalusers',
            },
        ),
    ]
