# Generated by Django 5.1.7 on 2025-04-08 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0005_signupuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='signupuser',
            name='dateUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
