# Generated by Django 5.1.7 on 2025-04-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0006_signupuser_datecreated_signupuser_dateupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signupuser',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
