# Generated by Django 5.2 on 2025-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0008_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
