# Generated by Django 5.2 on 2025-04-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0009_signupuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
