import os
import sys
import django

# Add the root directory of the project to the Python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Set DJANGO_SETTINGS_MODULE to point to the correct path
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "startup.settings")

# Setup Django
django.setup()


# Now you can import models from landingPage
from landingPage.models import Country


data = [
    ("Afghanistan", "Afghan"),
    ("Albania", "Albanian"),
    ("Algeria", "Algerian"),
    ("Andorra", "Andorran"),
    ("Angola", "Angolan"),
    ("Argentina", "Argentinian"),
    ("Australia", "Australian"),
    ("Austria", "Austrian"),
    ("Bahamas", "Bahamian"),
    ("Bahrain", "Bahraini"),
    ("Bangladesh", "Bangladeshi"),
    ("Barbados", "Barbadian"),
    ("Belgium", "Belgian"),
    ("Belize", "Belizean"),
    ("Benin", "Beninese"),
    ("Bhutan", "Bhutanese"),
    ("Bolivia", "Bolivian"),
    ("Botswana", "Batswana"),
    ("Brazil", "Brazilian"),
    ("Brunei", "Bruneian"),
    ("Bulgaria", "Bulgarian"),
    ("Burkina Faso", "Burkinabé"),
    ("Burundi", "Burundian"),
    ("Cambodia", "Cambodian"),
    ("Cameroon", "Cameroonian"),
    ("Canada", "Canadian"),
    ("Chad", "Chadian"),
    ("Chile", "Chilean"),
    ("China", "Chinese"),
    ("Colombia", "Colombian"),
    ("Comoros", "Comorian"),
    ("Congo", "Congolese"),
    ("Costa Rica", "Costa Rican"),
    ("Croatia", "Croatian"),
    ("Cuba", "Cuban"),
    ("Cyprus", "Cypriot"),
    ("Denmark", "Danish"),
    ("Djibouti", "Djiboutian"),
    ("Dominican Republic", "Dominican"),
    ("Ecuador", "Ecuadorian"),
    ("Egypt", "Egyptian"),
    ("El Salvador", "Salvadoran"),
    ("Estonia", "Estonian"),
    ("Ethiopia", "Ethiopian"),
    ("Fiji", "Fijian"),
    ("Finland", "Finnish"),
    ("France", "French"),
    ("Gabon", "Gabonese"),
    ("Gambia", "Gambian"),
    ("Georgia", "Georgian"),
    ("Germany", "German"),
    ("Ghana", "Ghanaian"),
    ("Greece", "Greek"),
    ("Grenada", "Grenadian"),
    ("Guatemala", "Guatemalan"),
    ("Guinea", "Guinean"),
    ("Guyana", "Guyanese"),
    ("Haiti", "Haitian"),
    ("Honduras", "Honduran"),
    ("Hungary", "Hungarian"),
    ("Iceland", "Icelander"),
    ("India", "Indian"),
    ("Indonesia", "Indonesian"),
    ("Iran", "Iranian"),
    ("Iraq", "Iraqi"),
    ("Ireland", "Irish"),
    ("Israel", "Israeli"),
    ("Italy", "Italian"),
    ("Jamaica", "Jamaican"),
    ("Japan", "Japanese"),
    ("Jordan", "Jordanian"),
    ("Kazakhstan", "Kazakh"),
    ("Kenya", "Kenyan"),
    ("Kuwait", "Kuwaiti"),
    ("Laos", "Lao"),
    ("Latvia", "Latvian"),
    ("Lebanon", "Lebanese"),
    ("Lesotho", "Mosotho"),
    ("Liberia", "Liberian"),
    ("Libya", "Libyan"),
    ("Lithuania", "Lithuanian"),
    ("Luxembourg", "Luxembourger"),
    ("Madagascar", "Malagasy"),
    ("Malawi", "Malawian"),
    ("Malaysia", "Malaysian"),
    ("Maldives", "Maldivian"),
    ("Mali", "Malian"),
    ("Malta", "Maltese"),
    ("Mexico", "Mexican"),
    ("Moldova", "Moldovan"),
    ("Monaco", "Monegasque"),
    ("Mongolia", "Mongolian"),
    ("Morocco", "Moroccan"),
    ("Mozambique", "Mozambican"),
    ("Myanmar", "Burmese"),
    ("Namibia", "Namibian"),
    ("Nepal", "Nepali"),
    ("Netherlands", "Dutch"),
    ("New Zealand", "New Zealander"),
    ("Nicaragua", "Nicaraguan"),
    ("Niger", "Nigerien"),
    ("Nigeria", "Nigerian"),
    ("North Korea", "North Korean"),
    ("Norway", "Norwegian"),
    ("Oman", "Omani"),
    ("Pakistan", "Pakistani"),
    ("Palestine", "Palestinian"),
    ("Panama", "Panamanian"),
    ("Paraguay", "Paraguayan"),
    ("Peru", "Peruvian"),
    ("Philippines", "Filipino"),
    ("Poland", "Polish"),
    ("Portugal", "Portuguese"),
    ("Qatar", "Qatari"),
    ("Romania", "Romanian"),
    ("Russia", "Russian"),
    ("Rwanda", "Rwandan"),
    ("Saint Lucia", "Saint Lucian"),
    ("Saudi Arabia", "Saudi"),
    ("Senegal", "Senegalese"),
    ("Serbia", "Serbian"),
    ("Seychelles", "Seychellois"),
    ("Sierra Leone", "Sierra Leonean"),
    ("Singapore", "Singaporean"),
    ("Slovakia", "Slovak"),
    ("Somalia", "Somali"),
    ("South Africa", "South African"),
    ("South Korea", "South Korean"),
    ("Spain", "Spanish"),
    ("Sri Lanka", "Sri Lankan"),
    ("Sudan", "Sudanese"),
    ("Suriname", "Surinamese"),
    ("Sweden", "Swedish"),
    ("Switzerland", "Swiss"),
    ("Syria", "Syrian"),
    ("Tanzania", "Tanzanian"),
    ("Thailand", "Thai"),
    ("Togo", "Togolese"),
    ("Tunisia", "Tunisian"),
    ("Turkey", "Turkish"),
    ("Uganda", "Ugandan"),
    ("Ukraine", "Ukrainian"),
    ("United Arab Emirates", "Emirati"),
    ("United Kingdom", "British"),
    ("United States", "American"),
    ("Uruguay", "Uruguayan"),
    ("Venezuela", "Venezuelan"),
    ("Yemen", "Yemeni"),
    ("Zambia", "Zambian"),
]

# Insert each country if it doesn't already exist
for name, nationality in data:
    _, created = Country.objects.get_or_create(name=name, defaults={'nationality': nationality})
    if created:
        print(f"✅ Inserted: {name} - {nationality}")
    else:
        print(f"⚠️ Skipped (already exists): {name}")
